"use strict";

const fs = require("fs");
const path = require("path");
const store = require("../core/store");
const agents = require("../core/agents");

function run(args) {
  const type = args["--type"];
  const agentId = args["--agent-id"] || `${type}-${Date.now().toString(36)}`;

  if (!type || !["claude", "codex"].includes(type)) {
    console.error("Usage: acc install --type claude|codex [--agent-id <id>]");
    process.exit(1);
  }

  const projectDir = process.cwd();
  store.bootstrap(projectDir);
  agents.register(agentId, type, projectDir);

  if (type === "claude") {
    installClaude(agentId, projectDir);
  } else {
    installCodex(agentId, projectDir);
  }

  console.log(JSON.stringify({ installed: type, agentId, project: projectDir }));
}

function installClaude(agentId, projectDir) {
  const claudeDir = path.join(projectDir, ".claude", "hooks");
  fs.mkdirSync(claudeDir, { recursive: true });

  const commsRoot = store.commsRoot(projectDir);
  const hookPath = path.join(claudeDir, "acc-pre-tool-use.js");

  // Generate self-contained hook script with baked-in config
  const hookScript = generateClaudeHook(agentId, commsRoot);
  fs.writeFileSync(hookPath, hookScript);

  // Merge into .claude/settings.json (idempotent)
  const settingsPath = path.join(projectDir, ".claude", "settings.json");
  mergeClaudeSettings(settingsPath, hookPath);
}

function installCodex(agentId, projectDir) {
  const accBin = path.resolve(__dirname, "../../bin/acc.js");
  console.error(`Codex agent "${agentId}" registered.`);
  console.error(`Use the wrapper: node ${path.resolve(__dirname, "../hooks/codex-wrapper.sh")} ${agentId} <codex-cmd>`);
}

function generateClaudeHook(agentId, commsRoot) {
  // Build the hook as a plain string array to avoid template literal escaping issues
  const lines = [];
  lines.push('#!/usr/bin/env node');
  lines.push('"use strict";');
  lines.push('// Generated by acc install — do not edit manually.');
  lines.push('// Agent: ' + agentId + ' | Comms: ' + commsRoot);
  lines.push('');
  lines.push('const fs = require("fs");');
  lines.push('const path = require("path");');
  lines.push('');
  lines.push('const AGENT_ID = ' + JSON.stringify(agentId) + ';');
  lines.push('const COMMS_ROOT = ' + JSON.stringify(commsRoot) + ';');
  lines.push('const LEASES_DIR = path.join(COMMS_ROOT, "leases");');
  lines.push('const INBOX_DIR = path.join(COMMS_ROOT, "inbox", AGENT_ID);');
  lines.push('const RECEIPTS_DIR = path.join(COMMS_ROOT, "receipts");');
  lines.push('const TASKS_DIR = path.join(COMMS_ROOT, "tasks");');
  lines.push('');
  lines.push('function readJSON(fp) {');
  lines.push('  try { return JSON.parse(fs.readFileSync(fp, "utf8")); } catch { return null; }');
  lines.push('}');
  lines.push('');
  lines.push('function escapeRegex(s) {');
  lines.push('  return s.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&");');
  lines.push('}');
  lines.push('');
  lines.push('function matchesGlob(filePath, pattern) {');
  lines.push('  var norm = filePath.replace(/\\\\/g, "/");');
  lines.push('  var pat = pattern.replace(/\\\\/g, "/");');
  lines.push('  if (typeof path.matchesGlob === "function") return path.matchesGlob(norm, pat);');
  lines.push('  var regex = "", i = 0;');
  lines.push('  while (i < pat.length) {');
  lines.push('    var ch = pat[i];');
  lines.push('    if (ch === "*" && pat[i + 1] === "*") { regex += ".*"; i += 2; if (pat[i] === "/") i++; }');
  lines.push('    else if (ch === "*") { regex += "[^/]*"; i++; }');
  lines.push('    else if (ch === "?") { regex += "[^/]"; i++; }');
  lines.push('    else { regex += escapeRegex(ch); i++; }');
  lines.push('  }');
  lines.push('  return new RegExp("^" + regex + "$").test(norm);');
  lines.push('}');
  lines.push('');
  lines.push('function canonicalize(filePath, root) {');
  lines.push('  var abs = path.resolve(root, filePath);');
  lines.push('  var rootPrefix = root.endsWith(path.sep) ? root : root + path.sep;');
  lines.push('  if (!abs.startsWith(rootPrefix) && abs !== root) return filePath;');
  lines.push('  return path.relative(root, abs).replace(/\\\\/g, "/");');
  lines.push('}');
  lines.push('');
  lines.push('function checkLease(filePath) {');
  lines.push('  if (!fs.existsSync(LEASES_DIR)) return null;');
  lines.push('  var now = Math.floor(Date.now() / 1000);');
  lines.push('  var files = fs.readdirSync(LEASES_DIR).filter(function(f) { return f.endsWith(".json"); });');
  lines.push('  for (var fi = 0; fi < files.length; fi++) {');
  lines.push('    var lease = readJSON(path.join(LEASES_DIR, files[fi]));');
  lines.push('    if (!lease || lease.expiresAt <= now || lease.owner === AGENT_ID) continue;');
  lines.push('    for (var pi = 0; pi < lease.files.length; pi++) {');
  lines.push('      if (matchesGlob(filePath, lease.files[pi]) || filePath === lease.files[pi]) return lease;');
  lines.push('    }');
  lines.push('  }');
  lines.push('  return null;');
  lines.push('}');
  lines.push('');
  lines.push('function taskStatusFromFile(taskPath) {');
  lines.push('  var task = readJSON(taskPath);');
  lines.push('  if (!task) return null;');
  lines.push('  if (task.status !== "queued" && task.status !== "in_progress" && task.status !== "blocked") return null;');
  lines.push('  return task;');
  lines.push('}');
  lines.push('');
  lines.push('function getTaskContext() {');
  lines.push('  if (!fs.existsSync(TASKS_DIR)) return null;');
  lines.push('  var files = fs.readdirSync(TASKS_DIR).filter(function(f) { return f.endsWith(".json"); });');
  lines.push('  if (files.length === 0) return null;');
  lines.push('  var tasks = [];');
  lines.push('  for (var i = 0; i < files.length; i++) {');
  lines.push('    var t = taskStatusFromFile(path.join(TASKS_DIR, files[i]));');
  lines.push('    if (t) tasks.push(t);');
  lines.push('  }');
  lines.push('  if (tasks.length === 0) return null;');
  lines.push('  var out = ["[ACC] Active tasks:"];');
  lines.push('  for (var ti = 0; ti < tasks.length; ti++) {');
  lines.push('    var t2 = tasks[ti];');
  lines.push('    var owner = t2.owner || "unowned";');
  lines.push('    var tasksFlags = [];');
  lines.push('    if (t2.unfailable) tasksFlags.push("unfailable");');
  lines.push('    if (t2.expectedArtifacts && t2.expectedArtifacts.length > 0) tasksFlags.push("artifacts=" + t2.expectedArtifacts.join(","));');
  lines.push('    var flags = tasksFlags.length > 0 ? " [" + tasksFlags.join(", ") + "]" : "";');
  lines.push('    out.push("  " + t2.id + ": " + JSON.stringify(t2.title) + " (" + t2.status + ", owner=" + owner + ", priority=" + t2.priority + ")" + flags);');
  lines.push('    if (t2.objective) out.push("    objective: " + JSON.stringify(t2.objective));');
  lines.push('    if (t2.scope && t2.scope.length > 0) out.push("    scope: " + t2.scope.join(", "));');
  lines.push('  }');
  lines.push('  return out.join("\\n");');
  lines.push('}');
  lines.push('');
  lines.push('function getInboxContext() {');
  lines.push('  if (!fs.existsSync(INBOX_DIR)) return null;');
  lines.push('  var now = Math.floor(Date.now() / 1000);');
  lines.push('  var receipts = readJSON(path.join(RECEIPTS_DIR, AGENT_ID + ".json")) || {};');
  lines.push('  var pending = [];');
  lines.push('  var files = fs.readdirSync(INBOX_DIR).filter(function(f) { return f.endsWith(".json"); });');
  lines.push('  for (var i = 0; i < files.length; i++) {');
  lines.push('    var msg = readJSON(path.join(INBOX_DIR, files[i]));');
  lines.push('    if (!msg || msg.timestamp + msg.ttl < now) continue;');
  lines.push('    if (receipts[msg.id] && receipts[msg.id] !== "pending") continue;');
  lines.push('    pending.push(msg);');
  lines.push('  }');
  lines.push('  if (pending.length === 0) return null;');
  lines.push('  var out = ["[ACC] You have " + pending.length + " pending message(s):"];');
  lines.push('  for (var j = 0; j < pending.length; j++) {');
  lines.push('    var m = pending[j];');
  lines.push('    var flags = [];');
  lines.push('    if (m.blocking) flags.push("BLOCKING");');
  lines.push('    if (m.requiresAck) flags.push("ACK-REQUIRED");');
  lines.push('    var flagStr = flags.length > 0 ? " [" + flags.join(", ") + "]" : "";');
  lines.push('    var fileStr = m.files && m.files.length > 0 ? " (files: " + m.files.join(", ") + ")" : "";');
  lines.push('    var safeBody = JSON.stringify(m.body);');
  lines.push('    out.push("  From " + m.from + flagStr + ": " + safeBody + fileStr);');
  lines.push('    out.push("    [msg-id: " + m.id + "]");');
  lines.push('  }');
  lines.push('  return out.join("\\n");');
  lines.push('}');
  lines.push('');
  lines.push('(async () => {');
  lines.push('  var input = "";');
  lines.push('  for await (var chunk of process.stdin) input += chunk;');
  lines.push('  var payload = JSON.parse(input);');
  lines.push('  var toolName = payload.tool_name || "";');
  lines.push('  var toolInput = payload.tool_input || {};');
  lines.push('  var filePath = toolInput.file_path || toolInput.path || "";');
  lines.push('');
  lines.push('  // For Bash commands — inject context only, never deny');
  lines.push('  if (toolName === "Bash") {');
  lines.push('    var msgCtx = getInboxContext();');
  lines.push('    var taskCtx = getTaskContext();');
  lines.push('    var ctx = [msgCtx, taskCtx].filter(Boolean).join("\\n\\n");');
  lines.push('    if (ctx) process.stdout.write(JSON.stringify({ permissionDecision: "allow", additionalContext: ctx }));');
  lines.push('    return;');
  lines.push('  }');
  lines.push('');
  lines.push('  // For Edit/Write/MultiEdit — check leases');
  lines.push('  if (filePath) {');
  lines.push('    var projectRoot = path.resolve(COMMS_ROOT, "..");');
  lines.push('    var canonical = canonicalize(filePath, projectRoot);');
  lines.push('    var lease = checkLease(canonical);');
  lines.push('    if (lease) {');
  lines.push('      var remaining = lease.expiresAt - Math.floor(Date.now() / 1000);');
  lines.push('      process.stdout.write(JSON.stringify({');
  lines.push('        permissionDecision: "deny",');
  lines.push('        reason: "[ACC] File " + JSON.stringify(canonical) + " is leased by " + lease.owner + " (lease: " + lease.id + ", expires in " + remaining + "s). Wait or ask them to release it."');
  lines.push('      }));');
  lines.push('      return;');
  lines.push('    }');
  lines.push('  }');
  lines.push('');
  lines.push('  // Inject pending messages as context');
  lines.push('  var msgCtx = getInboxContext();');
  lines.push('  var taskCtx = getTaskContext();');
  lines.push('  var context = [msgCtx, taskCtx].filter(Boolean).join("\\n\\n");');
  lines.push('  if (context) {');
  lines.push('    process.stdout.write(JSON.stringify({ permissionDecision: "allow", additionalContext: context }));');
  lines.push('    return;');
  lines.push('  }');
  lines.push('  // Fast path — no conflicts, no messages');
  lines.push('})();');

  return lines.join('\n') + '\n';
}

function mergeClaudeSettings(settingsPath, hookPath) {
  let settings = {};
  if (fs.existsSync(settingsPath)) {
    try {
      settings = JSON.parse(fs.readFileSync(settingsPath, "utf8"));
    } catch {
      settings = {};
    }
  }

  if (!settings.hooks) settings.hooks = {};
  if (!settings.hooks.PreToolUse) settings.hooks.PreToolUse = [];

  const hookCommand = `node "$CLAUDE_PROJECT_DIR/.claude/hooks/acc-pre-tool-use.js"`;

  // Idempotent: check if our hook already exists
  const existing = settings.hooks.PreToolUse.find((entry) =>
    entry.hooks && entry.hooks.some((h) => h.command && h.command.includes("acc-pre-tool-use"))
  );

  if (!existing) {
    settings.hooks.PreToolUse.push({
      matcher: "Edit|Write|MultiEdit|Bash",
      hooks: [{
        type: "command",
        command: hookCommand,
        timeout: 10,
      }],
    });
  }

  fs.mkdirSync(path.dirname(settingsPath), { recursive: true });
  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + "\n");
}

module.exports = { run };
