"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");
const { spawnSync } = require("child_process");

const ACC_BIN = path.resolve(__dirname, "../bin/acc.js");
const FIXTURES_DIR = path.join(__dirname, "fixtures", "claude-settings");

let passed = 0;
let failed = 0;

function assert(condition, label) {
  if (condition) {
    passed++;
    console.log(`  ✓ ${label}`);
  } else {
    failed++;
    console.error(`  ✗ ${label}`);
  }
}

function assertEqual(actual, expected, label) {
  assert(actual === expected, `${label} (expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)})`);
}

function freshRepo() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "acc-install-claude-"));
  fs.writeFileSync(path.join(dir, "README.md"), "repo\n", "utf8");
  return dir;
}

function cleanup(dir) {
  fs.rmSync(dir, { recursive: true, force: true });
}

function runInstall(repoDir, agentId) {
  return spawnSync("node", [ACC_BIN, "install", "--type", "claude", "--agent-id", agentId], {
    cwd: repoDir,
    encoding: "utf8",
  });
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function copyFixture(name, targetPath) {
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.copyFileSync(path.join(FIXTURES_DIR, name), targetPath);
}

function countAccEntries(settings) {
  const entries = (((settings || {}).hooks || {}).PreToolUse || []);
  return entries.filter((entry) => Array.isArray(entry.hooks) && entry.hooks.some((hook) => {
    return hook && typeof hook.command === "string" && hook.command.includes("acc-pre-tool-use.js");
  })).length;
}

function testFreshRepoBootstrap() {
  console.log("\n── install claude bootstraps fresh repo ──");
  const repoDir = freshRepo();

  const result = runInstall(repoDir, "claude-main");
  assertEqual(result.status, 0, "install exits 0");

  const payload = JSON.parse(result.stdout.trim());
  assertEqual(payload.installed, "claude", "payload reports claude install");
  assertEqual(payload.agentId, "claude-main", "payload reports chosen agent id");

  const commsRoot = path.join(repoDir, ".agent-comms");
  const hookPath = path.join(repoDir, ".claude", "hooks", "acc-pre-tool-use.js");
  const settingsPath = path.join(repoDir, ".claude", "settings.json");

  assert(fs.existsSync(path.join(commsRoot, "inbox")), "bootstrap creates inbox dir");
  assert(fs.existsSync(path.join(commsRoot, "leases")), "bootstrap creates leases dir");
  assert(fs.existsSync(path.join(commsRoot, "receipts")), "bootstrap creates receipts dir");
  assert(fs.existsSync(path.join(commsRoot, "tasks")), "bootstrap creates tasks dir");
  assert(fs.existsSync(hookPath), "bootstrap writes Claude hook");
  assert(fs.existsSync(settingsPath), "bootstrap writes Claude settings");

  const hook = fs.readFileSync(hookPath, "utf8");
  assert(hook.includes("Generated by ACC install"), "hook contains ACC managed marker");
  assert(hook.includes('const AGENT_ID = "claude-main";'), "hook bakes in agent id");
  assert(!hook.includes("Werkstatt"), "hook does not reference Werkstatt paths");

  const settings = readJson(settingsPath);
  assertEqual(countAccEntries(settings), 1, "settings contain exactly one ACC PreToolUse entry");

  cleanup(repoDir);
}

function testRerunIsIdempotent() {
  console.log("\n── install claude rerun is idempotent ──");
  const repoDir = freshRepo();

  const first = runInstall(repoDir, "claude-main");
  const second = runInstall(repoDir, "claude-main");

  assertEqual(first.status, 0, "first install succeeds");
  assertEqual(second.status, 0, "second install succeeds");

  const settings = readJson(path.join(repoDir, ".claude", "settings.json"));
  assertEqual(countAccEntries(settings), 1, "rerun does not duplicate ACC settings entry");

  cleanup(repoDir);
}

function testExistingSettingsArePreserved() {
  console.log("\n── install claude preserves unrelated settings ──");
  const repoDir = freshRepo();
  const settingsPath = path.join(repoDir, ".claude", "settings.json");
  copyFixture("valid-existing.json", settingsPath);

  const result = runInstall(repoDir, "claude-main");
  assertEqual(result.status, 0, "install succeeds with valid existing settings");

  const settings = readJson(settingsPath);
  assertEqual(settings.theme, "solarized", "top-level settings key preserved");
  assert(Array.isArray(settings.hooks.PreToolUse), "PreToolUse remains an array");
  assertEqual(settings.hooks.PreToolUse[0].matcher, "Read", "existing hook entry preserved");
  assertEqual(countAccEntries(settings), 1, "ACC entry added once alongside existing hook");

  cleanup(repoDir);
}

function testMalformedSettingsRefuseInstall() {
  console.log("\n── install claude refuses malformed settings ──");
  const repoDir = freshRepo();
  const settingsPath = path.join(repoDir, ".claude", "settings.json");
  copyFixture("malformed.json", settingsPath);
  const before = fs.readFileSync(settingsPath, "utf8");

  const result = runInstall(repoDir, "claude-main");
  assert(result.status !== 0, "install fails for malformed settings");
  assert(result.stderr.includes("settings.json"), "stderr mentions settings path");
  assertEqual(fs.readFileSync(settingsPath, "utf8"), before, "malformed settings file left unchanged");
  assert(!fs.existsSync(path.join(repoDir, ".agent-comms")), ".agent-comms not created on malformed settings failure");

  cleanup(repoDir);
}

function testUnmanagedHookRefuseInstall() {
  console.log("\n── install claude refuses unmanaged existing hook ──");
  const repoDir = freshRepo();
  const hookPath = path.join(repoDir, ".claude", "hooks", "acc-pre-tool-use.js");
  fs.mkdirSync(path.dirname(hookPath), { recursive: true });
  fs.writeFileSync(hookPath, "#!/usr/bin/env node\nconsole.log('user-managed');\n", "utf8");
  const before = fs.readFileSync(hookPath, "utf8");

  const result = runInstall(repoDir, "claude-main");
  assert(result.status !== 0, "install fails for unmanaged hook");
  assert(result.stderr.includes("acc-pre-tool-use.js"), "stderr mentions hook path");
  assertEqual(fs.readFileSync(hookPath, "utf8"), before, "unmanaged hook file left unchanged");
  assert(!fs.existsSync(path.join(repoDir, ".agent-comms")), ".agent-comms not created on unmanaged hook failure");
  assert(!fs.existsSync(path.join(repoDir, ".claude", "settings.json")), "settings file not created on unmanaged hook failure");

  cleanup(repoDir);
}

function main() {
  testFreshRepoBootstrap();
  testRerunIsIdempotent();
  testExistingSettingsArePreserved();
  testMalformedSettingsRefuseInstall();
  testUnmanagedHookRefuseInstall();

  if (failed > 0) {
    console.error(`\n${failed} test(s) failed, ${passed} passed`);
    process.exit(1);
  }
  console.log(`\n${passed} test(s) passed`);
}

main();
